# Generated by Django 5.1.1 on 2024-10-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_ensino', '0002_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
