# Generated by Django 5.1.1 on 2024-10-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_ensino', '0006_alter_customuser_email_alter_customuser_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mundo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
