# Generated by Django 5.1.1 on 2024-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_ensino', '0007_customuser_fase_customuser_mundo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fase',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
