# Generated by Django 5.1.1 on 2024-10-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_ensino', '0008_alter_customuser_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(blank=True, default='avt22', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cor_perfil',
            field=models.TextField(blank=True, default='rgba(255, 0, 0, 0)', null=True),
        ),
    ]
