# Generated by Django 5.1.1 on 2024-10-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_ensino', '0009_customuser_avatar_customuser_cor_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cor_perfil',
            field=models.TextField(blank=True, default='#D90429', null=True),
        ),
    ]
