# Generated by Django 5.1.1 on 2024-10-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_ensino', '0012_alter_customuser_avatar_alter_customuser_cor_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, default='avt22', max_length=5, null=True),
        ),
    ]
